name: Keep Alive

on:
  schedule:
    # Runs at midnight on day 1 of every month
    - cron: '0 0 1 * *'

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
